//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public int idtodo { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> feito { get; set; }
    
        public virtual Todo Todo { get; set; }
    }
}
